apiVersion: v1
kind: Secret
metadata:
  name: mes-secrets
type: Opaque
data:
  access_key_id: Q1I1TDFSQzNXT0VJTTk5MzY0TVo=
  secret: RG1uRElDeUxhWGpaM3JCSU9qTDAyc3RxeFRGVkxUWHJwTVFoeFY2NQ==
---
# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-api
  template:
    metadata:
      labels:
        app: codification-api
    spec:
      containers:
        - name: api
          image: ahmed577/primepredict:main
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: https://user-ahmed-mlflow.user.lab.sspcloud.fr
            - name: MLFLOW_MODEL_FREQ_NAME
              value: model_freq
            - name: MLFLOW_MODEL_FREQ_VERSION
              value: "1"
            - name: MLFLOW_MODEL_REG_NAME
              value: model_reg
            - name: MLFLOW_MODEL_REG_VERSION
              value: "1"
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mes-secrets
                  key: access_key_id
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mes-secrets
                  key: secret
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
