name: Image Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - notebooks/**
      - README.md
      
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # latest python minor
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install unittest2
          pip install pylint
      - name: Run unit tests
        run: |
          python -m unittest unit_test/test_build_pipeline.py
          python -m unittest unit_test/test_model_evaluate.py
          python -m unittest unit_test/test_models.py
      - name: Lint
        run: |
          pylint src/pipeline --fail-under=7
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ahmed577/primepredict

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
